services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chat
      - MONGO_INITDB_ROOT_PASSWORD=chat
  mongoexpress:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONODB_ADMINUSERNAME=kodat
      - ME_CONFIG_MONODB_ADMINUSERNAME=kodat
      - ME_CONFIG_MONODB_ADMINUSERNAME=mongodb
volumes:
  mongo: {}